
' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [FilmController]
  [FilmResolver]

  [FilmService]

  [Repository<Film>]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB film" {
    [Tabelle film]
    [Tabelle titel]
    [Tabelle abbildung]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [FilmController]
[RequestLoggerMiddleware] ~~> [FilmResolver]

[FilmController] ..> [FilmService]
[FilmResolver] ..> [FilmService]
[FilmService] ..> [Repository<Film>]

[Repository<Film>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle film]
[TypeORM] ~~> [Tabelle titel]
[TypeORM] ~~> [Tabelle abbildung]

[FilmController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[FilmService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

@enduml
